export const actionTypes = {
  LOGIN_LOADING: 'LOGIN_LOADING',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',

  CATEGORY_LOADING: 'CATEGORY_LOADING',
  CATEGORY_SUCCESS: 'CATEGORY_SUCCESS',
  CATEGORY_FAIL: 'CATEGORY_FAIL',
};
